---
title: "Final Project Proposal"
output: github_document
---

### The group members (names and UNIs):

Shuhong Xiang(sx2289), Xinyi Wang(xw2759), Ling Tuo(lt2812), Zhixing Wu(zw2709), Yali Zhai(yz3956)

### The tentative project title: 
Dog Bite Analysis in NYC

### The motivation for this project 

The phenomenon of dog bite seems to be uncommon nowadays, which might make some people be afraid of dogs. In addition, the severe consequence of dog bite such as physical injuries and potential diseases has aroused wide public concern. This project is designed to analyze potential associated indicators for the dog bite.



### The intended final products/the planned analyses/visualization

From the dog bite dataset, we will utilize data of bite to figure out the distribution and analyze the trend of bite rate by making a histogram. From the NYC dog licensing dataset, we make a line chart with the license issued date to find out whether there is an association between bite rate and license.


The three datasets have a common variable: borough. Therefore, we will use three 
histograms to show the counts of dog licenses, dog bite, and dog run based on 
the boroughs separately. We will also analyze the data with the different 
policies in different areas, i.e. off-leash vs. dog run.  

We make a pie chart to show the proportions of different genders in the biting dogs and another one to show the proportions of different breeds. Thus we can analyze if the dog bite is associated with gender and breed.

Our major challenges are large size of datasets with a large amount of missing values, finding a common variable to analyze/compare three tables, converting zipcodes into boroughs in order to match data.

### Planned timeline: 
Nov 7-13:  submit proposal, and project review meeting

Nov14-17: get three datasets tidy

Nov18-24: analyze datasets, make plots and write report

Nov25-Dec1: revise report and make web pages

Dec2-Dec4: make a video

Dec 5: submit final work

(Group meeting: Every Thursday 9.30 pm)

### Anticipated data sources
Dog bite dataset:           
https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg

NYC dog licensing dataset: 
https://data.cityofnewyork.us/Health/NYC-Dog-Licensing-Dataset/nu7n-tubp

Dog runs and off-leash Areas dataset: 
https://data.cityofnewyork.us/Recreation/Directory-of-Dog-Runs-and-Off-Leash-Areas/ipbu-mtcs

