---
title: "Final Project Proposal"
output: github_document
---

### The group members (names and UNIs):

Shuhong Xiang(sx2289), Xinyi Wang(xw2759), Ling Tuo(lt2812), Zhixing Wu(zw2709), Yali Zhai(yz3956)

### The tentative project title: 

Dog Lifetime License Analysis in Allegheny County in PA


### The motivation for this project 

Dog license acquisition seems to be complicated by states but may assist decreasing dog bites efficiently and make it safer for people to keep dogs. We take Allegheny County, PA as an example since they have special regulations of dog lifetime licenses. This project is designed to analyze potential associated indicators and distributions of the dog life license.


### The intended final products/the planned analyses/visualization

The dog lifetime license has four types, which are Lifetime Male or Female Dog, Lifetime Senior Citizen Female or Male Dog, Lifetime Spayed Female or Neutered Male Dog and Lifetime Senior Citizen Female and Male Gog,  according to the price from high to low. We use a bar chart to show the count of each type to study the association between the license types and price.
The licence valid date could be analysed using line charts to show the changing trend. The four license types based on price considerations could be compared throughout the time period. Additionally, time of valid date would be studied to show owners’ preference for AM or PM transactions.
We are going to draw a histogram to find out the most popular color (if the dog has more than one color, it will be categorized as “mix”) of dogs in  Allegheny County. According to zipcode, a heatmap can be used to visualize where people prefer to get their dogs lifetime license.

Our major challenge is the large size of the datasets, we need to find some reasonable criteria to filter the valid data. Also, for the dog breed, we need to create a new category under color called “mixed” to replace the multiple combinations of different colors. 


### Planned timeline: 
Nov 7-18:  submit proposal, and project review meeting

Nov 18-24: get a tidy dataset, analyze datasets, make plots and write report

Nov 25-Dec 1: revise report and make web pages

Dec 2-Dec 4: make a video

Dec 5: submit final work

(Group meeting: Every Thursday 9.30 pm)

### Anticipated data sources

http://infoportal.alleghenycounty.us/dogdata/default.aspx



